import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Renomme toutes les colonnes camelCase en snake_case pour compatibilité
 * DBeaver / clients SQL qui n'utilisent pas de guillemets (PostgreSQL lowercase les identifiants).
 */
export class CamelCaseToSnakeCase1738765000000 implements MigrationInterface {
  name = 'CamelCaseToSnakeCase1738765000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const renames: [string, string, string][] = [
      ['products', 'categoryId', 'category_id'],
      ['products', 'shopId', 'shop_id'],
      ['products', 'brandId', 'brand_id'],
      ['products', 'collectionId', 'collection_id'],
      ['products', 'careInstructions', 'care_instructions'],
      ['products', 'customSizeChart', 'custom_size_chart'],
      ['products', 'madeIn', 'made_in'],
      ['products', 'createdAt', 'created_at'],
      ['products', 'updatedAt', 'updated_at'],
      ['variants', 'productId', 'product_id'],
      ['variants', 'createdAt', 'created_at'],
      ['variants', 'updatedAt', 'updated_at'],
      ['images', 'productId', 'product_id'],
      ['images', 'publicId', 'public_id'],
      ['images', 'createdAt', 'created_at'],
      ['collections', 'displayName', 'display_name'],
      ['collections', 'isActive', 'is_active'],
      ['collections', 'createdAt', 'created_at'],
      ['collections', 'updatedAt', 'updated_at'],
      ['categories', 'imageUrl', 'image_url'],
      ['categories', 'videoUrl', 'video_url'],
      ['categories', 'sizeChart', 'size_chart'],
      ['categories', 'createdAt', 'created_at'],
      ['categories', 'updatedAt', 'updated_at'],
      ['brands', 'logoUrl', 'logo_url'],
      ['brands', 'megaMenuImage1', 'mega_menu_image_1'],
      ['brands', 'megaMenuImage2', 'mega_menu_image_2'],
      ['brands', 'megaMenuVideo1', 'mega_menu_video_1'],
      ['brands', 'megaMenuVideo2', 'mega_menu_video_2'],
      ['brands', 'createdAt', 'created_at'],
      ['brands', 'updatedAt', 'updated_at'],
      ['shops', 'shippingPolicy', 'shipping_policy'],
      ['shops', 'returnPolicy', 'return_policy'],
      ['shops', 'createdAt', 'created_at'],
      ['shops', 'updatedAt', 'updated_at'],
      ['addresses', 'userId', 'user_id'],
      ['addresses', 'postalCode', 'postal_code'],
      ['addresses', 'additionalInfo', 'additional_info'],
      ['addresses', 'isDefault', 'is_default'],
      ['addresses', 'createdAt', 'created_at'],
      ['addresses', 'updatedAt', 'updated_at'],
      ['users', 'firstName', 'first_name'],
      ['users', 'lastName', 'last_name'],
      ['users', 'isVerified', 'is_verified'],
      ['users', 'createdAt', 'created_at'],
      ['users', 'updatedAt', 'updated_at'],
      ['carts', 'sessionId', 'session_id'],
      ['carts', 'createdAt', 'created_at'],
      ['carts', 'updatedAt', 'updated_at'],
      ['cart_items', 'cartId', 'cart_id'],
      ['cart_items', 'variantId', 'variant_id'],
      ['cart_items', 'createdAt', 'created_at'],
      ['orders', 'cartId', 'cart_id'],
      ['orders', 'userId', 'user_id'],
      ['orders', 'couponId', 'coupon_id'],
      ['orders', 'customerInfo', 'customer_info'],
      ['orders', 'shippingAddress', 'shipping_address'],
      ['orders', 'billingAddress', 'billing_address'],
      ['orders', 'paymentIntentId', 'payment_intent_id'],
      ['orders', 'trackingNumber', 'tracking_number'],
      ['orders', 'discountAmount', 'discount_amount'],
      ['orders', 'paidAt', 'paid_at'],
      ['orders', 'shippedAt', 'shipped_at'],
      ['orders', 'deliveredAt', 'delivered_at'],
      ['orders', 'createdAt', 'created_at'],
      ['orders', 'updatedAt', 'updated_at'],
      ['order_emails', 'orderId', 'order_id'],
      ['order_emails', 'emailType', 'email_type'],
      ['order_emails', 'recipientEmail', 'recipient_email'],
      ['order_emails', 'errorMessage', 'error_message'],
      ['order_emails', 'sentAt', 'sent_at'],
      ['order_emails', 'createdAt', 'created_at'],
      ['coupons', 'discountType', 'discount_type'],
      ['coupons', 'discountValue', 'discount_value'],
      ['coupons', 'expiresAt', 'expires_at'],
      ['coupons', 'maxUses', 'max_uses'],
      ['coupons', 'usedCount', 'used_count'],
      ['coupons', 'minPurchaseAmount', 'min_purchase_amount'],
      ['coupons', 'isActive', 'is_active'],
      ['coupons', 'createdAt', 'created_at'],
      ['coupons', 'updatedAt', 'updated_at'],
      ['stock_notifications', 'productId', 'product_id'],
      ['stock_notifications', 'variantId', 'variant_id'],
      ['stock_notifications', 'isNotified', 'is_notified'],
      ['stock_notifications', 'notifiedAt', 'notified_at'],
      ['stock_notifications', 'createdAt', 'created_at'],
      ['stock_notifications', 'updatedAt', 'updated_at'],
    ];

    for (const [table, oldCol, newCol] of renames) {
      await queryRunner.query(
        `ALTER TABLE "${table}" RENAME COLUMN "${oldCol}" TO ${newCol}`,
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const renames: [string, string, string][] = [
      ['products', 'category_id', 'categoryId'],
      ['products', 'shop_id', 'shopId'],
      ['products', 'brand_id', 'brandId'],
      ['products', 'collection_id', 'collectionId'],
      ['products', 'care_instructions', 'careInstructions'],
      ['products', 'custom_size_chart', 'customSizeChart'],
      ['products', 'made_in', 'madeIn'],
      ['products', 'created_at', 'createdAt'],
      ['products', 'updated_at', 'updatedAt'],
      ['variants', 'product_id', 'productId'],
      ['variants', 'created_at', 'createdAt'],
      ['variants', 'updated_at', 'updatedAt'],
      ['images', 'product_id', 'productId'],
      ['images', 'public_id', 'publicId'],
      ['images', 'created_at', 'createdAt'],
      ['collections', 'display_name', 'displayName'],
      ['collections', 'is_active', 'isActive'],
      ['collections', 'created_at', 'createdAt'],
      ['collections', 'updated_at', 'updatedAt'],
      ['categories', 'image_url', 'imageUrl'],
      ['categories', 'video_url', 'videoUrl'],
      ['categories', 'size_chart', 'sizeChart'],
      ['categories', 'created_at', 'createdAt'],
      ['categories', 'updated_at', 'updatedAt'],
      ['brands', 'logo_url', 'logoUrl'],
      ['brands', 'mega_menu_image_1', 'megaMenuImage1'],
      ['brands', 'mega_menu_image_2', 'megaMenuImage2'],
      ['brands', 'mega_menu_video_1', 'megaMenuVideo1'],
      ['brands', 'mega_menu_video_2', 'megaMenuVideo2'],
      ['brands', 'created_at', 'createdAt'],
      ['brands', 'updated_at', 'updatedAt'],
      ['shops', 'shipping_policy', 'shippingPolicy'],
      ['shops', 'return_policy', 'returnPolicy'],
      ['shops', 'created_at', 'createdAt'],
      ['shops', 'updated_at', 'updatedAt'],
      ['addresses', 'user_id', 'userId'],
      ['addresses', 'postal_code', 'postalCode'],
      ['addresses', 'additional_info', 'additionalInfo'],
      ['addresses', 'is_default', 'isDefault'],
      ['addresses', 'created_at', 'createdAt'],
      ['addresses', 'updated_at', 'updatedAt'],
      ['users', 'first_name', 'firstName'],
      ['users', 'last_name', 'lastName'],
      ['users', 'is_verified', 'isVerified'],
      ['users', 'created_at', 'createdAt'],
      ['users', 'updated_at', 'updatedAt'],
      ['carts', 'session_id', 'sessionId'],
      ['carts', 'created_at', 'createdAt'],
      ['carts', 'updated_at', 'updatedAt'],
      ['cart_items', 'cart_id', 'cartId'],
      ['cart_items', 'variant_id', 'variantId'],
      ['cart_items', 'created_at', 'createdAt'],
      ['orders', 'cart_id', 'cartId'],
      ['orders', 'user_id', 'userId'],
      ['orders', 'coupon_id', 'couponId'],
      ['orders', 'customer_info', 'customerInfo'],
      ['orders', 'shipping_address', 'shippingAddress'],
      ['orders', 'billing_address', 'billingAddress'],
      ['orders', 'payment_intent_id', 'paymentIntentId'],
      ['orders', 'tracking_number', 'trackingNumber'],
      ['orders', 'discount_amount', 'discountAmount'],
      ['orders', 'paid_at', 'paidAt'],
      ['orders', 'shipped_at', 'shippedAt'],
      ['orders', 'delivered_at', 'deliveredAt'],
      ['orders', 'created_at', 'createdAt'],
      ['orders', 'updated_at', 'updatedAt'],
      ['order_emails', 'order_id', 'orderId'],
      ['order_emails', 'email_type', 'emailType'],
      ['order_emails', 'recipient_email', 'recipientEmail'],
      ['order_emails', 'error_message', 'errorMessage'],
      ['order_emails', 'sent_at', 'sentAt'],
      ['order_emails', 'created_at', 'createdAt'],
      ['coupons', 'discount_type', 'discountType'],
      ['coupons', 'discount_value', 'discountValue'],
      ['coupons', 'expires_at', 'expiresAt'],
      ['coupons', 'max_uses', 'maxUses'],
      ['coupons', 'used_count', 'usedCount'],
      ['coupons', 'min_purchase_amount', 'minPurchaseAmount'],
      ['coupons', 'is_active', 'isActive'],
      ['coupons', 'created_at', 'createdAt'],
      ['coupons', 'updated_at', 'updatedAt'],
      ['stock_notifications', 'product_id', 'productId'],
      ['stock_notifications', 'variant_id', 'variantId'],
      ['stock_notifications', 'is_notified', 'isNotified'],
      ['stock_notifications', 'notified_at', 'notifiedAt'],
      ['stock_notifications', 'created_at', 'createdAt'],
      ['stock_notifications', 'updated_at', 'updatedAt'],
    ];

    for (const [table, oldCol, newCol] of renames) {
      await queryRunner.query(
        `ALTER TABLE "${table}" RENAME COLUMN ${oldCol} TO "${newCol}"`,
      );
    }
  }
}
